apiVersion: apps/v1
kind: Deployment
metadata:
  name: yhft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yhft
  template:
    metadata:
      labels:
        app: yhft
    spec:
      containers:
      - image: okteto.dev/yhft:latest
        name: yhft
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "156a5848-3065-43a9-a45a-ae0f332c7c69"
        - name: Vless_Path
          value: "/vl33bbs5"
        - name: Vmess_UUID
          value: "156a5848-3065-43a9-a45a-ae0f332c7c69"
        - name: Vmess_Path
          value: "/vm66vv3346"
        - name: Share_Path
          value: "/v2link"
